# Generated by Django 5.0.6 on 2024-09-13 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gender'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.maritalstatus'),
        ),
    ]
