# Generated by Django 5.0.6 on 2024-09-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orders_main_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usercode',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Transaction_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trandate', models.DateTimeField(auto_now_add=True)),
                ('rundate', models.DateTimeField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('Processed', 'Processed'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('accType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.acctype')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('tran_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transaction_codes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
