# Generated by Django 5.0.6 on 2024-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bonus_tran_rundate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_bonus',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
