# Generated by Django 5.0.6 on 2024-09-21 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_bonus_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='admin_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
