# Generated by Django 5.0.6 on 2024-10-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pointsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsmodel',
            old_name='Points',
            new_name='points',
        ),
    ]
