# Generated by Django 5.0.6 on 2024-10-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_points_pointsmodel_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsmodel',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pointsmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointsProd', to='home.products'),
        ),
    ]
