# Generated by Django 5.0.6 on 2024-10-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_pointsmodel_points_alter_pointsmodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsmodel',
            name='product',
        ),
    ]
